version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-alarm-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - ollama
    networks:
      - financial-alarm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial-alarm-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - financial-alarm-network

  ollama:
    image: ollama/ollama:latest
    container_name: financial-alarm-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - financial-alarm-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  ollama_data:

networks:
  financial-alarm-network:
    driver: bridge 